accounts_index:
    path:     /
    defaults: { _controller: "AppBundle:Accounts:index" }
    methods:  GET

accounts_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Accounts:show" }
    methods:  GET

accounts_new:
    path:     /new
    defaults: { _controller: "AppBundle:Accounts:new" }
    methods:  [GET, POST]

accounts_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Accounts:edit" }
    methods:  [GET, POST]

accounts_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Accounts:delete" }
    methods:  DELETE
